name: npstar
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.23
  - pandas>=1.5
  - geopandas>=0.12
  - rasterio>=1.3
  - matplotlib>=3.6
  - tqdm>=4.65
  - scikit-learn>=1.2
  - shap>=0.42
  - openpyxl>=3.1
  - pip
  - pip:
      - richdem>=0.3.4
      - pyflwdir>=0.5.5
      - notebook>=7.0
